FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS testrunner
WORKDIR /src
COPY *.sln .
COPY src/GPONMonitor/*.csproj ./src/GPONMonitor/
COPY tests/*.csproj ./tests/
RUN dotnet restore ./GPONMonitor.sln
COPY . .
WORKDIR /src/tests
ENTRYPOINT ["dotnet", "test", "--logger:trx", "--results-directory:/var/temp"]
