version: '3.5'

services:
  gponmonitor.tests:
    image: bartekkois/gponmonitor.tests:1.0.8
    volumes:
      - ./temp:/var/temp
      - /etc/localtime:/etc/localtime:ro
    build:
      context: .
      dockerfile: ./Dockerfile.tests
