version: '3.5'

services:
  gponmonitor:
    image: bartekkois/gponmonitor:1.0.17
    restart: always
    volumes:
      - /docker/GPONMonitor/devicesconfiguration.json:/app/devicesconfiguration.json:ro
    ports:
      - "5001:8080"
    build:
      context: .
      dockerfile: ./Dockerfile
