FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS testrunner
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
WORKDIR /src
COPY *.sln .
COPY src/GPONMonitor/*.csproj ./src/GPONMonitor/
COPY tests/*.csproj ./tests/
RUN dotnet restore ./GPONMonitor.sln
COPY . .
WORKDIR /src/tests
ENTRYPOINT ["dotnet", "test", "--logger:trx", "--results-directory:/var/temp"]
