version: '3.5'

services:
  gponmonitor:
    image: bartekkois/gponmonitor:1.0.16
    restart: always
    volumes:
      - /docker/GPONMonitor/devicesconfiguration.json:/app/devicesconfiguration.json:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5001:8080"
